final Map<String, String> typeEmojis = {
  'normal': '🐻',
  'fire': '🔥',
  'water': '💧',
  'electric': '⚡',
  'grass': '🌿',
  'ice': '❄️',
  'fighting': '🥊',
  'poison': '☠️',
  'ground': '🌍',
  'flying': '🦅',
  'psychic': '🔮',
  'bug': '🐛',
  'rock': '🪨',
  'ghost': '👻',
  'dragon': '🐉',
  'dark': '🌑',
  'steel': '🛡️',
  'fairy': '🧚',
};
